"""
Two-Factor Authentication (TOTP) endpoints.

POST /auth/2fa/setup    — generate TOTP secret + QR code URI
POST /auth/2fa/verify   — verify TOTP code and enable 2FA
POST /auth/2fa/disable  — disable 2FA (requires current TOTP code)
POST /auth/2fa/validate — validate TOTP at login (called after password check)
"""

import base64
import io
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.dependencies import get_current_active_user
from app.core.database import get_db
from app.models.user import User

try:
    import pyotp
    import qrcode
    TOTP_AVAILABLE = True
except ImportError:
    TOTP_AVAILABLE = False

router = APIRouter()


def _require_totp():
    if not TOTP_AVAILABLE:
        raise HTTPException(
            status_code=501,
            detail="2FA not available — install pyotp and qrcode: pip install pyotp qrcode[pil]",
        )


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------

class TOTPSetupResponse(BaseModel):
    secret: str
    otpauth_uri: str
    qr_code_base64: str   # PNG image as base64 for frontend QR display


class TOTPVerifyRequest(BaseModel):
    code: str


class TOTPDisableRequest(BaseModel):
    code: str


class TOTPValidateRequest(BaseModel):
    user_id: str
    code: str


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.post(
    "/setup",
    response_model=TOTPSetupResponse,
    summary="Set up 2FA — generate TOTP secret and QR code",
    description=(
        "Generates a new TOTP secret for the authenticated user and returns a QR code "
        "URI and base64-encoded PNG image. The user must then verify the code with "
        "`POST /auth/2fa/verify` to actually enable 2FA."
    ),
)
async def setup_2fa(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user),
):
    _require_totp()

    secret = pyotp.random_base32()
    totp = pyotp.TOTP(secret)
    uri = totp.provisioning_uri(
        name=current_user.email,
        issuer_name="AdvisorAI",
    )

    # Generate QR code PNG as base64
    img = qrcode.make(uri)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    qr_b64 = base64.b64encode(buf.getvalue()).decode()

    # Store secret temporarily (not yet active — user must verify first)
    current_user.otp_secret = secret
    await db.commit()

    return TOTPSetupResponse(secret=secret, otpauth_uri=uri, qr_code_base64=qr_b64)


@router.post(
    "/verify",
    summary="Verify TOTP code and enable 2FA",
    description=(
        "Validates the 6-digit code from the authenticator app against the temporary secret "
        "generated by `/auth/2fa/setup`. On success, 2FA is permanently enabled."
    ),
)
async def verify_2fa(
    payload: TOTPVerifyRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user),
):
    _require_totp()

    if not current_user.otp_secret:
        raise HTTPException(status_code=400, detail="Run /auth/2fa/setup first")

    totp = pyotp.TOTP(current_user.otp_secret)
    if not totp.verify(payload.code, valid_window=1):
        raise HTTPException(status_code=400, detail="Invalid TOTP code")

    current_user.otp_enabled = True
    await db.commit()
    return {"status": "ok", "message": "2FA enabled successfully"}


@router.post(
    "/disable",
    summary="Disable 2FA",
    description="Disables 2FA for the current user. Requires a valid current TOTP code as confirmation.",
)
async def disable_2fa(
    payload: TOTPDisableRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user),
):
    _require_totp()

    if not current_user.otp_enabled or not current_user.otp_secret:
        raise HTTPException(status_code=400, detail="2FA is not enabled")

    totp = pyotp.TOTP(current_user.otp_secret)
    if not totp.verify(payload.code, valid_window=1):
        raise HTTPException(status_code=400, detail="Invalid TOTP code")

    current_user.otp_enabled = False
    current_user.otp_secret = None
    await db.commit()
    return {"status": "ok", "message": "2FA disabled"}


@router.get(
    "/status",
    summary="Get 2FA status",
    description="Returns whether 2FA is currently enabled for the authenticated user.",
)
async def get_2fa_status(
    current_user: User = Depends(get_current_active_user),
):
    return {
        "otp_enabled": current_user.otp_enabled,
        "has_secret": current_user.otp_secret is not None,
    }


@router.post(
    "/validate",
    summary="Validate TOTP at login (2FA second step)",
    description=(
        "Called after a login attempt returns `2fa_required`. "
        "Validates the TOTP code and issues JWT tokens if correct."
    ),
)
async def validate_2fa_at_login(
    payload: TOTPValidateRequest,
    db: AsyncSession = Depends(get_db),
):
    _require_totp()

    from sqlalchemy import select as _select
    result = await db.execute(_select(User).where(User.id == payload.user_id))
    user = result.scalar_one_or_none()

    if not user or not user.is_active or not user.otp_enabled or not user.otp_secret:
        raise HTTPException(status_code=400, detail="Invalid request")

    totp = pyotp.TOTP(user.otp_secret)
    if not totp.verify(payload.code, valid_window=1):
        raise HTTPException(status_code=400, detail="Invalid TOTP code")

    from app.core.security import create_access_token, create_refresh_token
    from app.schemas.user import Token
    access_token  = create_access_token(data={"sub": str(user.id)})
    refresh_token = create_refresh_token(data={"sub": str(user.id)})
    return Token(access_token=access_token, refresh_token=refresh_token)
